services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn portfolio.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ORIGIN_ALLOW_ALL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: ENV
        sync: false
      - key: DATABASE_URL           
        sync: false
      - key: USE_CLOUDINARY
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USE_TLS
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DJANGO_ADMIN_URL
        sync: false
      - key: STATIC_URL
        sync: false
      - key: MEDIA_URL
        sync: false
      - key: STATIC_ROOT
        sync: false
      - key: MEDIA_ROOT
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: SECURE_SSL_REDIRECT
        sync: false
      - key: LOG_LEVEL
        sync: false
      - key: REST_FRAMEWORK_DEFAULT_PERMISSION_CLASSES
        sync: false
      - key: REST_FRAMEWORK_DEFAULT_AUTHENTICATION_CLASSES
        sync: false
      - key: PAGINATION_PAGE_SIZE
        sync: false
      - key: TIME_ZONE
        sync: false
      - key: LANGUAGE_CODE
        sync: false
      - key: FEATURE_X_ENABLED
        sync: false
      - key: SITE_TITLE
        sync: false
